name: ozon-to-google-sheets

services:
  app:
    image: "ghcr.io/sotchenkov/ozon_to_google_sheets:0.1.0@sha256:6c4c10fc02c7dd1446fff6d18a1ff9b61e8cb6336c49d07393b00205f9aac6be"
    pull_policy: always
    env_file:
      - ${OZON_ENV_FILE:-.env}
    init: true
    restart: "no"
    read_only: true
    volumes:
      - type: bind
        source: ./logs
        target: /app/logs
      - type: bind
        source: ./secrets
        target: /app/secrets
        read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
